### PR TITLE
Add dune-workspace to dune.config.path_suffixes

### PR DESCRIPTION
**Pull request by smorimoto**
Ref:

- https://dune.readthedocs.io/en/stable/reference/index.html
- https://github.com/ocamllabs/vscode-ocaml-platform/blob/5c984b4715f0437cecafcbed3cc16790a0ac95fa/src/dune_formatter.ml#L35

### CODE REVIEW

**Comment by notpeter** [comment]
@cla-bot

**Comment by smorimoto** [comment]
Is the bot really working?

**Comment by notpeter** [comment]
It would appear as if cla-bot is having some trouble.
Can you manually sign the ZED CLA: https://zed.dev/cla
And then we can get this merged.

**Comment by smorimoto** [comment]
Done!

**Pull request merged**
